version: '3.6'
services: 
    postgres:
        image: 'postgres:12-alpine'
        restart: unless-stopped
        env_file:
            - ./.env-docker
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
            - POSTGRES_MULTIPLE_DATABASES=mhmarketaccount,mhmarketrental,mhmarketconfig,mhmarketmarket
        container_name: postgresql-mh
        ports: 
            - "5432:5432"
        volumes: 
            - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
networks:
    postgres-network:
        driver: mhnetwork

