version: '3.6'
services: 
    postgres:
        image: 'postgres:12-alpine'
        restart: unless-stopped
        env_file:
            - ./.env-docker
        environment: 
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_MULTIPLE_DATABASES=mhmarketaccount,mhmarketrental,mhmarketconfig,mhmarketmarket
        container_name: postgresql-mh
        ports: 
            - "5432:5432"
        volumes: 
            - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    pgadmin-compose:
        image: dpage/pgadmin4
        environment: 
            PGADMIN_DEFAULT_EMAIL: "hoanggg2110@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "Giacbavanh@2110"
        ports: 
            - "16543:80"
        depends_on: 
            - postgres    